### ISSUE TITLE
Use code for another extension

### ISSUE THREAD

**Issue by apazureck** [anacierdem/vscode-requirejs#15]
Hi,

I have an extension, where I need to provide a goto functionallity. Would it be ok to copy and modify your code?

Cheers,

Andreas

**Comment by anacierdem** [comment]
Hi,

It is OK as long as you give credit to this repository.

Best,

**Comment by apazureck** [comment]
No cando :) Of course I'll give credit, but I cannot directly call functions of your repo, as I have to do some changes to your code to make it work.

Thanks and best regards
