### ISSUE TITLE
doBackwardsSearch issues

### ISSUE THREAD

**Issue by michaelw85** [anacierdem/vscode-requirejs#18]
```
  /**
   * Searches for a character backwards inside fullText discarding spaces, tabs and newlines
   * Returns the found index or false if not found.
   * @param {Number} offset offset at which we start the search from
   * @param {String} searchFor a single character to search for
   */
   var doBackwardsSearch = function(offset, searchFor) {
   var currentChar;
   var found = false;
    
   //Do backwards search
   do {
     currentChar = fullText[offset];
     if(currentChar == searchFor) {
       found = true;
     }
     offset--;
   if(found)
     return offset;
   } while(offset >= 0 && (currentChar == " " || currentChar == "\t" || currentChar == "\n" || currentChar == "\r"));
     return false;
   }
```
I think this function has multiple issues:

1) This function never returns the character searching for!
`while(offset >= 0 && (currentChar == " " || currentChar == "\t" || currentChar == "\n" || currentChar == "\r"));`<br />  
While the offset is bigger/equal to 0 **AND** expects the character to be space or tab or newline or carriage return. The description says it should ignore these characters.<br />
Since this function should only matches the character you search for it already ignores anything that does not match so I think the while should just contain offset >= 0.<br />
I even think this function can be replaced with native `lastIndexOf` https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/String/lastIndexOf

2) When the character searching for is found we set `found = true` but after that we still deduct from the offset. Resulting in the character offset - 1. Is this intended? According to the description it should return the index of the character which it does not atm.

3) This function return false if nothing is found. Native js functions usually return -1 if nothing found. I would suggest using the same pattern.

Lets me know what you think.
Michael.

**Comment by anacierdem** [comment]
1. Yes and it does not need to if there is another character other than the searched one except newline/space etc. Changing the description to be more specific.
2. Changing the description again, this is intended. The purpose of this function is finding the position of the last character that is not the given character excluding newline/spaces.
3. I do not intend to  match native js funtionality? This will make later checks more complicated IMO.

Closing this issue as it is not an actual issue but your comments on this function.

**Comment by michaelw85** [comment]
1) Ok, the function name is misleading improving the description will help.
2) Ok, but it does not exclude spaces at the moment.
3) Matching standards makes it easier for others to work with these methods. It was just a suggestion no need to change it if you don't feel the need.

I will try to add unit tests soon to match current functionality then you can judge if the outcome of the function is as expected.
