### ISSUE TITLE
Add support for require.config

### ISSUE THREAD

**Issue by anacierdem** [anacierdem/vscode-requirejs#30]

**Comment by prantlf** [comment]
I implemented this requirement by using the requirejs module itself. It ensures compatibility with the original module path resolution. I can send you a PR for 986b0d2690fdbb3d8f183b080bfc033d896480a3 from the branch [use-require-config](https://github.com/prantlf/vscode-requirejs/commits/use-require-config) in my fork, if you like this approach.

I use it currently in a large project with more than a dozen of components and plugins, which divides the components using RequireJS bundles. I included a couple of simple project examples to demonstrate various workspace settings in the branch [project-examples](https://github.com/prantlf/vscode-requirejs/tree/project-examples/examples) in my fork, for which I could send you a PR too.

This means a departure from implementing the requirejs logic in the editor extension to leveraging the `requirejs` functionality directly For example, you may not need to implement parsing of JavaScript modules yourself to fix #37. The `amodro-trace` abstraction of RequireJS does it for you, for example.

What do you think?

**Comment by anacierdem** [comment]
Seems nice to me. My only consideration would be performance as the current codebase is trying to find shortest path to the destination module. As you say you are currently using your approach in a large project this may be a non-issue.

Please send me a PR including the examples and I'll have a closer look and merge as necessary, if it is OK for you.

**Comment by prantlf** [comment]
I put the `console.time()` and the `console.timeEnd()` around the call to the `initializeRequireJs` and also around the original code performing the module path resolution and around the new `resolveModulePath` call. The `initializeRequireJs` takes more time, when it needs to evaluate the `configFile`, as expected, but not so much. Measuring `resolveModulePath` didn't show a significant difference between the original and the `requirejs.toUrl` based implementation. A don't know, if a project with hundreds of require `paths` would make a difference, but I wouldn't want to maintain such one... ;-)

Without configFile
------------------

I opened `testFiles` and `examples/single-component`, both two times, when doing the "Go To Definition" tests below:

    initializeRequireJs: 1.205ms
    initializeRequireJs: 2.633ms
    initializeRequireJs: 0.797ms
    initializeRequireJs: 0.855ms

With configFile
---------------

I opened `examples/two-components` four times, when doing the "Go To Definition" tests below

    initializeRequireJs: 1.781ms
    initializeRequireJs: 1.550ms
    initializeRequireJs: 1.915ms
    initializeRequireJs: 4.317ms

Original resolveModulePath
--------------------------

I used "Go To Definition" in `testFiles` and `examples/single-component` projects; opening the projects two times and executing "Go To Definition" two times:

    testFiles:
      resolveModulePath: 1.400ms
      resolveModulePath: 1.044ms
      resolveModulePath: 0.713ms
      resolveModulePath: 0.702ms

    examples/single-component:
      resolveModulePath: 0.836ms
      resolveModulePath: 0.767ms
      resolveModulePath: 0.782ms
      resolveModulePath: 0.467ms

New resolveModulePath
---------------------

I used "Go To Definition" in `testFiles`, `examples/single-component` and `examples/two-components` projects; opening the projects two times and executing "Go To Definition" two times:

    testFiles:
      resolveModulePath: 1.012ms
      resolveModulePath: 0.717ms
      resolveModulePath: 0.637ms
      resolveModulePath: 0.884ms

    examples/single-component:
      resolveModulePath: 0.805ms
      resolveModulePath: 0.456ms
      resolveModulePath: 6.467ms
      resolveModulePath: 0.942ms

    examples/two-components:
      resolveModulePath: 0.587ms
      resolveModulePath: 0.755ms
      resolveModulePath: 0.578ms
      resolveModulePath: 0.542ms

Finally, I tried opening real-world project a couple of times and performing "Go To Definition" there. I was opening other projects between consecutive openings of the real-world one. The `initializeRequireJs` took a little more time, but the important times of `resolveModulePath` didn't change.

    initializeRequireJs: 8.671ms
    initializeRequireJs: 3.588ms
    initializeRequireJs: 1.632ms
    initializeRequireJs: 2.769ms

    resolveModulePath: 1.525ms
    resolveModulePath: 0.519ms
    resolveModulePath: 1.124ms
    resolveModulePath: 0.747ms
    resolveModulePath: 0.805ms
    resolveModulePath: 0.619ms
    resolveModulePath: 0.795ms
    resolveModulePath: 0.513ms

I attached the real-world project configuration as [real-world.zip](https://github.com/anacierdem/vscode-requirejs/files/1359043/real-world.zip).

**Comment by prantlf** [comment]
Please, have a look at #46 - it is the integration of the requirejs NPM module.
I opened #47 too - three sample projects demonstrating different extension configurations.
I'm looking for your feedback :-)

**Comment by prantlf** [comment]
I looked once more at the possibilities to parse the RequireJS configuration file.

    Test              Time
    -------------------------
    testEvalConfig    0.930ms
    testAmodroConfig  9.500ms

Parsing the RequireJS configuration file using the `esprima` parser takes significantly longer, than executing the file using `eval()`. However, it is safer. Also, it is performed just once, when a project is opened - during `activate(context)`. Using `amodro-trace/config` might be preferred to `eval()`, in the end.

**Comment by anacierdem** [comment]
Hi,

Thank you for all your detailed work. I have once used eval, but it is far more risky. I'll investigate your changes in detail when I have the time. This may take a few weeks if you dont mind. 

I'm currently really busy doing other things. But his will not remain unresolved :)

**Comment by prantlf** [comment]
No problem, take your time. I'm afraid, that I will have a lot of other changes for review in that time :-) I may ask you some questions in the meanwhile, though :-)
