### ISSUE TITLE
Implement Autocompletion

### ISSUE THREAD

**Issue by anacierdem** [anacierdem/vscode-requirejs#43]

**Comment by BrightSoul** [comment]
Yeah, I saw it's currently using a regexp to find the implementation on the target module which is not failproof.
https://github.com/anacierdem/vscode-requirejs/blob/83228a3916882bc64a636106e83eecc2edcc2499/extension.js#L223

I think it's better to parse the module source by using textmate, which is provided by Visual Studio Code. See here:
[https://github.com/Microsoft/vscode/issues/46281](https://github.com/Microsoft/vscode/issues/46281)

I forked your repository, I might do some experimentation on my spare time.

**Comment by anacierdem** [comment]
@prantlf was once working on migrating the project to esprima. Don' know why gave up.

I have an idea;

Let's use vscode.executeCompletionItemProvider based on the found target module?

I'll work on this.

**Comment by anacierdem** [comment]
Not the way I've anticipated, but I've implemented a crude version.

I suggest writing some tests to cover very basic use cases for this implementation.

**Comment by anacierdem** [comment]
Reverted eval version as it may cause more issues than it resolves.

**Comment by anacierdem** [comment]
Decided to close this one as I do not need this feature and no one requested it.
