### ISSUE TITLE
Module definition using arrow function - go to type

### ISSUE THREAD

**Issue by ladariha** [anacierdem/vscode-requirejs#50]
I'm using arrow functions like this:

```
define(["module1", "module2"], (module1, module2) =>{
   console.log("yeah");
})
```

In this case e.g. Go To Definition (aka Ctrl+Click on the string "module1" or "module2") does not work. It works if I change it to good old function instead of the arrow function syntax.

Would it be possible to support arrow functions as well? Thank you

**Comment by anacierdem** [comment]
This will be nice indeed. I'll have a look when I have the time.

**Comment by ladariha** [comment]
I have no experience with VSCode extensions, but I offer my help if you could point me to some direction :) It looks like maybe the change needed is in `getModulesWithPathFromRequireOrDefine` with tweaking the `params` regexp at line 78? At least it's the only place I've found string "function"

**Comment by anacierdem** [comment]
Must be fixed with 0.1.12!

You can review the diff if you are interested :)

**Comment by anacierdem** [comment]
There are a few issues remaining mainly on getRequireOrDefineStatements.

You may continue from there :)

**Comment by anacierdem** [comment]
I think I have resolved them. Can you try version 0.1.13 and verify?

**Comment by ladariha** [comment]
Awesome, thanks a lot for the quick implementation.
