### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by Han3Jim** [anacierdem/vscode-requirejs#59]
- Issue Type: `Performance`
- Extension Name: `require-js`
- Extension Version: `0.1.21`
- OS Version: `Darwin x64 17.7.0`
- VSCode version: `1.30.1`

:warning: Make sure to **attach** this file from your *home*-directory: `/Users/han/lici.require-js-unresponsive.cpuprofile.txt` :warning:

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by anacierdem** [comment]
I do not see this issue anymore. If anyone reproduces it, don't hesitate to open an issue.
