### ISSUE TITLE
Using " instead of '

### ISSUE THREAD

**Issue by nsergey82** [anacierdem/vscode-requirejs#60]
`define(['foo'],  function(foo)... ` works like a charm,
but `define(["foo"],  function(foo)...` does not. 
I didn't see any such example in getModulesWithPathFromRequireOrDefine.test.js

Would it be possible to tweak the regexp to match double quote literals (e.g., `val.replace(/["'\s\t\r\n\[\]]/gm, '')` or do you believe that "strings" shall not be used?

**Comment by anacierdem** [comment]
Using "strings" is completely legit. This is one of the shortcomings of the current case-by-case extension development without using a proper lexer. Feel free to add a test and send a PR!

**Comment by nsergey82** [comment]
Fixed by https://github.com/anacierdem/vscode-requirejs/pull/61
