### ISSUE TITLE
license

### ISSUE THREAD

**Issue by rwalle** [anacierdem/vscode-requirejs#68]
Hi,

This project does not currently have a license file, although I did see someone asking for permission to use the code in #15. I wonder if the author is interested in including an explicit license in the project? If not, and if I want to reuse the code, do I need to create a separate issue to ask for permission? (As I understand, #15 only grants permission to apazureck.) Thank you.

**Comment by anacierdem** [comment]
I’ll update the licence. If it is urgent, you can assume this is MIT
