### ISSUE TITLE
Modules with a different parameter name

### ISSUE THREAD

**Issue by anacierdem** [anacierdem/vscode-requirejs#8]
Modules with a different parameter name in require callback than the filename refuse to navigate with caret on referenced module name.

1) ctrl+click does not work (but should, it's valid usage)
```
define([
    'foo/Bar'
], function (bar) { // small case "b" at the beginning...ctrl+click does not work
});
```
2) ctrl+click does not work either (but should, it's still valid usage)
```
define([
    'foo/Bar'
], function (BarImpl) { // "Impl" suffix...ctrl+click does not work
});
```
3) this only works
```
define([
    'foo/Bar'
], function (Bar) { // exact match
});
```

**Comment by obrejla** [comment]
I click on last part of required module path...i.e. in `define(['foo/Bar'], function...`... I cmd+click on Bar.

**Comment by obrejla** [comment]
Maybe go to file works differently on case-insensitive Win and case-sensitive Mac ;)

**Comment by anacierdem** [comment]
committed f4dd8186233f0919692bcd82c033f28743e47772. Version 0.0.21. I think this solves your problem.

**Comment by obrejla** [comment]
Seems to work! Thanks ;)
