### ISSUE TITLE
Code Helper processes - 100% processor usage

### ISSUE THREAD

**Issue by obrejla** [anacierdem/vscode-requirejs#9]
Hi,

Code: 1.10.2
require-js: 0.0.23
OS: macOS Sierra

from time to time (but X times in a day ;) I'm observing Code Helper processes which consume about 100% of processor time. I think that it's caused by this extension because when I disable it, problems disappear ;)

It happens sometimes when I just move mouse over some `.js` element in opened file, then instead of e.g. `(local var) foo: any` I see only `Loading...` and that's all.

If there is a possibility to make some snapshot when it happens or provide more info, just tell me what to do.

Thanks.

**Comment by anacierdem** [comment]
Thank you for opening the issue I'll investigate shortly.

**Comment by obrejla** [comment]
Will try it, thanks.

**Comment by anacierdem** [comment]
Committed 385392cc796048aef64c550a86f330697d0e3b8f also. version 0.0.26

**Comment by anacierdem** [comment]
Did you have time to check? Haven't seen the issue on my tests after the update.

**Comment by obrejla** [comment]
Didn't see it either. Thanks.

**Comment by anacierdem** [comment]
Here with us again.

**Comment by anacierdem** [comment]
Fixed with 41b4001fb695747bef81fd57c5ac7f85fdfa9e3b

**Comment by anacierdem** [comment]
Follow up on #59
